openapi: 3.0.0
info:
  title: QuizzWhizz API
  version: 1.0.0
  description: API documentation for the QuizzWhizz application.
servers:
  - url: https://quizwhiz-backend.onrender.com/api/v1
paths:
  /auth/signup:
    post:
      summary: User signup
      description: Creates a new user account and returns a JWT token.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Divine
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
              required:
                - name
                - email
                - password
      responses:
        "201":
          description: User successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          email:
                            type: string
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        "403":
          description: Validation error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: Please provide a valid email, Please provide a password, Your password must be at least 8 characters long

        "409":
          description: Conflict, email already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: A user with that email already exists.
  /auth/login:
    post:
      summary: Log in a user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password123
              required:
                - email
                - password
      responses:
        "200":
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: jwt-token-example
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: user-id-example
                          name:
                            type: string
                            example: John Doe
                          email:
                            type: string
                            example: user@example.com
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: Email or password is incorrect.
